apiVersion: v1
kind: Service
metadata:
  name: {{ template "nexus.name" . }}
  labels:
    app: {{ template "nexus.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
    - port: {{ .Values.service.dockerProxyPort }}
      targetPort: {{ .Values.service.dockerProxyInternalPort }}
      protocol: TCP
      name: {{ .Values.service.dockerProxyName }}
    - port: {{ .Values.service.dockerHostedPort }}
      targetPort: {{ .Values.service.dockerHostedInternalPort }}
      protocol: TCP
      name: {{ .Values.service.dockerHostedName }}
  selector:
    app: {{ template "nexus.name" . }}
    release: {{ .Release.Name }}